feat(landing-page): landing page components
TengieMuzgi/liftlife-frontend pull request #5
Opened 2023-04-07 22:02 UTC by VanityEv

Obrazy z Pexels są trochę duże - trzeba będzie je skompresować

2023-04-08 19:07 UTC, Arwer234 requested changes

2023-04-08 19:07 UTC, Arwer234 commented on src/components/ContentBreaker/ContentBreaker.tsx
> +      <Box sx={{ backgroundColor: props.bgColor, width: '100%', p: 8 }}>
Może dobrym pomysłem byłoby przekazywanie całego zestawu `sx` do Box przez propa?

2023-04-08 19:07 UTC, Arwer234 commented on src/components/StepTile/StepTile.tsx
> +            <Typography variant="h5" align="center" display="block">
W jakim celu jest tutaj `display='block'`? :)

2023-04-08 19:07 UTC, Arwer234 commented on src/pages/LandingPage.tsx
> +        <ContentBreaker text="What are the benefits of working with us?" bgColor="secondary.main" />
Może bardziej intuicyjnym podejściem do przekazywania tekstu byłoby używanie `<ContentBreaker />` jako znacznika kontenerowego i tym samym obsługiwanie propa `children`?

2023-04-08 19:07 UTC, Arwer234 commented on src/pages/LandingPage.tsx
> +          <StepTile {...item} />
Czy `StepTile` ma przekazywany key?

2023-04-08 19:07 UTC, Arwer234 commented on src/pages/LandingPage.tsx
> +      <Grid container item direction={isMobile ? 'column' : 'row'} {...placeGridCenter} gap={3} wrap='nowrap'>
Tutaj pomocny może być pattern z MUI: https://mui.com/material-ui/react-grid/#ResponsiveGrid.tsx
Dla przykładu: `direction={{mobile:..., desktop:...}}`

2023-04-08 19:34 UTC, VanityEv commented on src/components/ContentBreaker/ContentBreaker.tsx
> +      <Box sx={{ backgroundColor: props.bgColor, width: '100%', p: 8 }}>
A ma to sens jeśli pozostałe `sx` są stałe?

2023-04-08 19:36 UTC, VanityEv commented on src/components/StepTile/StepTile.tsx
> +            <Typography variant="h5" align="center" display="block">
Zostało z testów (za bardzo rozpychały się bloki przy dużej ilości tekstu) zanim znalazłem winowajcę: grid item z `wrap`. Już poprawiam

2023-04-08 19:40 UTC, Arwer234 commented on src/components/ContentBreaker/ContentBreaker.tsx
> +      <Box sx={{ backgroundColor: props.bgColor, width: '100%', p: 8 }}>
Rzeczywiście nie ma, za dużo sernika :P

2023-04-08 20:28 UTC, VanityEv commented on src/pages/LandingPage.tsx
> +      <Grid container item direction={isMobile ? 'column' : 'row'} {...placeGridCenter} gap={3} wrap='nowrap'>
Poprawione :p

2023-04-08 20:28 UTC, VanityEv commented on src/pages/LandingPage.tsx
> +          <StepTile {...item} />
Już ma 💯

2023-04-08 20:29 UTC, VanityEv commented on src/pages/LandingPage.tsx
> +        <ContentBreaker text="What are the benefits of working with us?" bgColor="secondary.main" />
Done

2023-04-09 09:44 UTC, Arwer234 approved these changes

2023-04-09 12:59 UTC, merged